// <auto-generated />
using System;
using DShadow.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DShadow.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260718035254_InitialWeatherSchema")]
    partial class InitialWeatherSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("DShadow.Backend.Models.WeatherRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CloudsPercent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Humidity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Rain1h")
                        .HasColumnType("REAL");

                    b.Property<double>("Snow1h")
                        .HasColumnType("REAL");

                    b.Property<double>("SunAlpha")
                        .HasColumnType("REAL");

                    b.Property<double>("TempC")
                        .HasColumnType("REAL");

                    b.Property<double>("TimeEvent")
                        .HasColumnType("REAL");

                    b.Property<string>("TimeIso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimezoneOffset")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UpdateIntervalTime")
                        .HasColumnType("REAL");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeatherStateId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("REAL");

                    b.Property<double>("WindX")
                        .HasColumnType("REAL");

                    b.Property<double>("WindY")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("WeatherRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
